language: node_js
node_js: 
    - '6'

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "JayChenFE"
  - git config user.email "chenjiehwy@163.com"
  - git add . -f
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/JayChenFE/jaychenfe.github.io.git
